name: Android learning CI/CD

on:
  push:
    branches:
      - main
      - develop
      - 'qc/**'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Gant gradle permission
        run: chmod + x gradlew

      - name: Run ktLin
        run: .gradlew ktlintCheck
